-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT A.USER_ID) USERS
FROM USER_INFO A
JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;

# SELECT *
# FROM USER_INFO A
# JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
# WHERE GENDER = 1 AND SALES_DATE LIKE "2022-01%"
