-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) YEAR, MONTH(B.SALES_DATE) MONTH, COUNT(*) PUCHASED_USERS,
ROUND(COUNT(*) / 
    (
        SELECT COUNT(*)
        FROM USER_INFO A 
        WHERE A.JOINED LIKE "2021%"
    )
, 1) PUCHASED_RATIO
FROM USER_INFO A
JOIN 
(
    SELECT *
    FROM ONLINE_SALE 
    GROUP BY USER_ID
)
B ON A.USER_ID = B.USER_ID 
WHERE A.JOINED LIKE "2021%" 
GROUP BY YEAR, MONTH;

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT O.USER_ID) AS PUCHASEDUSERS, 
ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASEDRATIO
FROM USER_INFO U, ONLINE_SALE O
WHERE U.USER_ID = O.USER_ID AND YEAR(JOINED) = 2021
GROUP BY MONTH
ORDER BY YEAR ASC, MONTH ASC;