-- 코드를 입력하세요
SELECT n AS HOUR, IFNULL(COUNT, 0) COUNT
FROM (
    SELECT @N := @N + 1 AS n
    FROM ANIMAL_OUTS, ( SELECT @N := -1 FROM DUAL) NN
    LIMIT 24) AS T
LEFT JOIN
(
    SELECT (HOUR(DATETIME)) HOUR, COUNT(DATETIME) AS COUNT
    FROM  ANIMAL_OUTS
    GROUP BY HOUR
) AS A
ON A.HOUR = T.n
ORDER BY n;