-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
# SELECT *
FROM BOOK B
NATURAL JOIN AUTHOR A
NATURAL JOIN BOOK_SALES BS
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC