-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(PRODUCT.PRICE * OFFLINE_SALE.SALES_AMOUNT) AS SALES
# SELECT *
FROM PRODUCT
NATURAL JOIN OFFLINE_SALE
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;
